<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Director extends \App\Entity\Director implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".'*'."\0".'name' => [parent::class, 'name', null],
        "\0".'*'."\0".'performance' => [parent::class, 'performance', null],
        "\0".'*'."\0".'surname' => [parent::class, 'surname', null],
        "\0".'App\\Entity\\Person'."\0".'id' => ['App\\Entity\\Person', 'id', null],
        'id' => ['App\\Entity\\Person', 'id', null],
        'name' => [parent::class, 'name', null],
        'performance' => [parent::class, 'performance', null],
        'surname' => [parent::class, 'surname', null],
    ];

    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {
        if ($cloner !== null) {
            return;
        }

        self::createLazyGhost($initializer, [
            "\0".'App\\Entity\\Person'."\0".'id' => true,
        ], $this);
    }

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"], $properties['__isCloning']);

        return $properties;
    }
}
