<?php

namespace ContainerN1hf27T;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCatedraControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\CatedraController' shared autowired service.
     *
     * @return \App\Controller\CatedraController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/CatedraController.php';

        $container->services['App\\Controller\\CatedraController'] = $instance = new \App\Controller\CatedraController();

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\CatedraController', $container));

        return $instance;
    }
}
