<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container7UBC47x\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7UBC47x/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/Container7UBC47x.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\Container7UBC47x\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \Container7UBC47x\App_KernelTestDebugContainer([
    'container.build_hash' => '7UBC47x',
    'container.build_id' => '01608049',
    'container.build_time' => 1691405800,
], __DIR__.\DIRECTORY_SEPARATOR.'Container7UBC47x');
