<?php

namespace Container7UBC47x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGesdinet_Jwtrefreshtoken_Request_Extractor_RequestBodyService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'gesdinet.jwtrefreshtoken.request.extractor.request_body' shared service.
     *
     * @return \Gesdinet\JWTRefreshTokenBundle\Request\Extractor\RequestBodyExtractor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/gesdinet/jwt-refresh-token-bundle/Request/Extractor/ExtractorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/gesdinet/jwt-refresh-token-bundle/Request/Extractor/RequestBodyExtractor.php';

        return $container->privates['gesdinet.jwtrefreshtoken.request.extractor.request_body'] = new \Gesdinet\JWTRefreshTokenBundle\Request\Extractor\RequestBodyExtractor();
    }
}
